<?php
/**
 * ParsYar Enterprise Theme functions.
 *
 * Acts as a headless shell: the rendered <body> only contains a single
 * <div id="root"></div> mount point and the React/Tailwind bundle.
 *
 * @package ParsYar\Theme
 */

declare(strict_types=1);

defined( 'ABSPATH' ) || exit;

if ( ! defined( 'PARS_YAR_THEME_DIR' ) ) {
	define( 'PARS_YAR_THEME_DIR', get_template_directory() );
}
if ( ! defined( 'PARS_YAR_THEME_URL' ) ) {
	define( 'PARS_YAR_THEME_URL', get_template_directory_uri() );
}

/**
 * Enqueue the React SPA bundle. The build output lives in /spa/dist/
 * and is generated by Vite (see spa/package.json).
 */
add_action( 'wp_enqueue_scripts', static function (): void {
	$manifest_path = PARS_YAR_THEME_DIR . '/spa/dist/manifest.json';
	if ( ! file_exists( $manifest_path ) ) {
		// Dev / first-run fallback: emit a console hint instead of 404ing.
		add_action( 'wp_footer', static function (): void {
			echo '<!-- ParsYar SPA bundle not built. Run `npm run build` inside /spa. -->';
		} );
		return;
	}

	$manifest = json_decode( (string) file_get_contents( $manifest_path ), true );
	if ( ! is_array( $manifest ) ) {
		return;
	}

	$entry = $manifest['index.html'] ?? null;
	if ( ! is_array( $entry ) ) {
		return;
	}

	foreach ( (array) ( $entry['assets']['js'] ?? [] ) as $js ) {
		wp_enqueue_script(
			'pars-yar-spa-' . sanitize_key( wp_basename( (string) $js ) ),
			PARS_YAR_THEME_URL . '/spa/dist/' . ltrim( (string) $js, '/' ),
			[],
			null,
			true
		);
	}
	foreach ( (array) ( $entry['assets']['css'] ?? [] ) as $css ) {
		wp_enqueue_style(
			'pars-yar-spa-' . sanitize_key( wp_basename( (string) $css ) ),
			PARS_YAR_THEME_URL . '/spa/dist/' . ltrim( (string) $css, '/' ),
			[],
			null
		);
	}

	wp_localize_script( 'pars-yar-spa', 'parsYarBoot', [
		'rest'   => esc_url_raw( rest_url( 'pars-yar/v1/' ) ),
		'nonce'  => wp_create_nonce( 'wp_rest' ),
		'userId' => get_current_user_id(),
	] );
} );

/**
 * Render a single mount point.
 */
add_filter( 'template_include', static function ( $template ) {
	if ( is_page_template( 'spa.php' ) || is_page( 'pars-yar-app' ) ) {
		return PARS_YAR_THEME_DIR . '/spa.php';
	}
	return $template;
} );

/**
 * Register the "pars-yar-app" page on theme activation.
 */
add_action( 'after_switch_theme', static function (): void {
	$existing = get_page_by_path( 'pars-yar-app' );
	if ( ! $existing ) {
		wp_insert_post( [
			'post_title'   => 'ParsYar',
			'post_name'    => 'pars-yar-app',
			'post_status'  => 'publish',
			'post_type'    => 'page',
			'post_content' => 'ParsYar SPA mount point — do not edit.',
		] );
	}
} );
